### ISSUE TITLE
The (state) of expansion  of Hypothesis side bar always returns false

### ISSUE THREAD

**Issue by MohammadHader** [hypothesis/client#744] opened 2018-07-04 08:26 UTC
Important note: This bug happens on this branch: evidentpoint:configurable-sidebar-placement on this PR: https://github.com/hypothesis/client/pull/707

### Steps to reproduce
1. Open/close sidebar.
2. Put a break point inside the function onLayoutChange inside window.hypothesisConfig
3. notice the state object's result.

### Expected behaviour
It should return the actual state of expansion.
 
### Actual behaviour
It always returns false (Not expanded).

### Browser/system information
System: Ubuntu 18.04 LTS
Browser: Google chrome, Version 67.0.3396.87 (Official Build) (64-bit)

**Comment by robertknight** [comment] 2018-07-09 16:22
I was not able to reproduce the problem on this branch when using this test case:

```html
<html>
  <head>
    <meta charset="utf-8">
    <style>
.article {
  width: 500px;
  margin-left: auto;
  margin-right: auto;
  margin-bottom: 25px;
}
    </style>
  </head>
  <body>
    <article class="article">
      <h1>An article about things</h1>
      Lorem ipsum stuff.
    </article>
  <script>
    window.hypothesisConfig = () => {
      return {
        onLayoutChange: (...args) => console.log('Layout changed', args),
      };
    };
  </script>
  <script src="http://localhost:5000/embed.js"></script>
  </body>
</html>
```

What is different in your scenario?

**Comment by MohammadHader** [comment] 2018-07-12 07:36
The "onLayoutChange" always executes when the sidebar opens/close. However, when you try to print the state of expansion in "console.log('Layout changed', args)" it will always return (expanded = false)

**Comment by robertknight** [comment] 2021-03-18 11:48
I'm closing the issue because it no longer applies. We now have other functionality such as the side-by-side mode in PDFs which wouldn't work otherwise (see https://github.com/hypothesis/client/blob/5f0c5dc68fdfec4ced7b7f8c0cd1ac710fa99b3e/src/annotator/pdf-sidebar.js#L85).

**Closed by robertknight** 2021-03-18 11:48 UTC
