### ISSUE TITLE
H users can create annotations that appear in 3rd party namespaces

### ISSUE THREAD

**Issue by dwhly** [hypothesis/client#669] opened 2018-02-12 19:01 UTC
### Steps to reproduce
1. Go to elife. https://elifesciences.org/articles/27455  or possibly requires fragment to be at the end, as in: https://elifesciences.org/articles/27455#annotations:4tv-4hAkEei2joegde_0tw
2. Turn on chrome extension.
3. Login to H
4. Make an annotation.
5. Turn off chrome extension.
6. Click eLife annotations button to deploy their sidebar

### Expected behaviour
No H annotations should be visible in their "eLife" group

### Actual behaviour
The H annotation is visible.

### Browser/system information
Chrome

**Comment by judell** [comment] 2018-02-12 19:04
I would think it would require:

1a: Log out of eLife embed if logged in.

However, when I do that, I can't log into H on that page.

**Comment by judell** [comment] 2018-02-12 19:17
When I am logged out from all clients, and I visit https://elifesciences.org/articles/27455, and activate the H extension, I am seeing this JS complaint from elife code:

```
Error: Invalid HTML: <p class="paragraph">(<b>a</b>) Fitted dose response curves for five representative cells are highlighted in color, within the ensemble for a population of 59 cells from a single experiment (same data as <a href="#fig2">Figure 2</a>). (<b>b</b>) <math id="inf45"><mstyle displaystyle="true" scriptlevel="0"><mrow><mi>K</mi></mrow></mstyle></math> and <math id="inf46"><mstyle displaystyle="true" scriptlevel="0"><mrow><mi>H</mi></mrow></mstyle></math> parameter-fit uncertainty basins, with long and short axes obtained from eigendecomposition of the covariance matrix for each fit, with the highlighted cells corresponding to the same example cells as in panel (<b>a</b>). (<b>c</b>) Day-to-day variability in dose-response phenotype distributions. Distribution of parameter <math id="inf47"><mstyle displaystyle="true" scriptlevel="0"><mrow><mi>K</mi></mrow></mstyle></math> (top) and <math id="inf48"><mstyle displaystyle="true" scriptlevel="0"><mrow><mi>H</mi></mrow></mstyle></math> (bottom) from a single FRET experiment performed on different days. Together with the data from panels a-b (blue) an additional experiment is shown with 44 out of 45 cells. Shaded areas represent 95 % confidence intervals obtained by bootstrap resampling.</p>
    at n (index.js:281)
    at e.exports (index.js:68)
    at t.value (ToggleableCaption.js:52)
    at new t (ToggleableCaption.js:22)
    at main.js:75
    at Array.forEach (<anonymous>)
    at t (main.js:72)
    at main.js:97
    at NodeList.forEach (<anonymous>)
    at MutationObserver.<anonymous> (main.js:97)
```

Just me?

**Comment by judell** [comment] 2018-02-12 19:21
At a different URL, https://elifesciences.org/articles/26796, when I activate the H extension, there's no error, but also no sidebar appears.

**Comment by xolotl** [comment] 2018-02-12 19:26
I am not able to reproduce this issue as described in the original issue. But, I can view an annotation I made in the public layer using the Chrome extension while logged in to my Hypothesis namespace account in the eLife client when I follow a bouncer link to it: https://hyp.is/rR27JBApEeiEd5Pig7FV0Q/elifesciences.org/articles/27455

**Comment by judell** [comment] 2018-02-12 19:29
Which resolves to https://elifesciences.org/articles/27455#annotations:rR27JBApEeiEd5Pig7FV0Q if you have the extension. 

Or to via if not: https://via.hypothes.is/https://elifesciences.org/articles/27455#annotations:rR27JBApEeiEd5Pig7FV0Q

**Comment by judell** [comment] 2018-02-12 19:32
Tried annotating by way of https://elifesciences.org/articles/27455#annotations:rR27JBApEeiEd5Pig7FV0Q

![image](https://user-images.githubusercontent.com/46509/36115576-54ab956a-0fe8-11e8-948a-cdd194025f3b.png)

**Comment by judell** [comment] 2018-02-12 19:33
Now using the via URL:

![image](https://user-images.githubusercontent.com/46509/36115646-88d619c8-0fe8-11e8-8faf-cb533aa1a3f5.png)

**Comment by judell** [comment] 2018-02-12 19:35
Cannot delete the annotation I just made from the via URL in the extension:

![image](https://user-images.githubusercontent.com/46509/36115684-af8592f6-0fe8-11e8-8229-986760ffc3dc.png)

But can (and did) delete that annotation in the H instance provided by via.

**Comment by robertknight** [comment] 2018-02-19 15:57
I'm closing this issue because we haven't successfully reproduced it.

**Closed by robertknight** 2018-02-19 15:57 UTC
