### ISSUE TITLE
Triple-click annotation marked orphan; changes when switching groups

### ISSUE THREAD

**Issue by nickstenning** [hypothesis/client#109] opened 2016-09-15 10:08 UTC
### Steps to reproduce
1. Create an annotation at the start of a paragraph.
2. Triple-click to select the whole paragraph and click annotate.
3. [Observe no editor -- the annotation is apparently in the orphans tab.] Switch to another group.
4. [Observe annotation editor.] Switch back to prior group.
5. [Observe annotation editor.] Complete and save annotation.
6. [Observe annotation in "page notes" tab.]

### Expected behaviour
I'd expect:

- the selection on the page (in blue) to reflect the selected text of the annotation -- in this case it appears the annotation has no selection
- the visibility of the editor shouldn't change when switching groups
- the orphan/non-orphan status shouldn't change when switching groups
- the annotation/page note classification shouldn't change when saving an annotation

### Actual behaviour

Here's a screencast of me following the above steps using client master:

![](http://g.recordit.co/AWjjcjEuuH.gif)

### Browser/system information

- **Version**: 0.42.0
- **User agent**: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2859.0 Safari/537.36
- **URL**: https://localhost:5000/docs/help
- **Username**: foo
- **Date**: 15 Sep 2016 12:07:05 +0200

**Comment by robertknight** [comment] 2016-09-15 10:13
I can reproduce using https://hypothes.is/docs/help and selecting _exactly_ the same text as in the screencast.

In doing so, I see this error in the browser console:

```js
Uncaught (in promise) TypeError: Cannot read property 'nodeType' of undefined
    at Object.Util.getFirstTextNodeNotBefore (https://hypothes.is/assets/client/scripts/injector.bundle.js?bb3e58:4160:14)
    at BrowserRange.Range.BrowserRange.BrowserRange.normalize (https://hypothes.is/assets/client/scripts/injector.bundle.js?bb3e58:4531:24)
    at https://hypothes.is/assets/client/scripts/injector.bundle.js?bb3e58:1424:29
    at https://hypothes.is/assets/client/scripts/injector.bundle.js?bb3e58:1130:24
```

This is the same error I think as the PDF selection issue.

**Comment by robertknight** [comment] 2016-09-15 10:18
I just reproduced the issue a second time but didn't see any any error in the console.

**Comment by robertknight** [comment] 2016-09-15 10:33
I think the reason why the draft suddenly appears when switching groups may be related to the way that, when switching groups, we first unload _all_ annotations and then reload `drafts.unsaved()`.

**Comment by robertknight** [comment] 2016-09-15 10:40
OK, I've confirmed the above. Changing the `_resetAnnotations()` function in `widget-controller.js` to only unload saved annotations when switching groups fixes the problem:

```js
  function _resetAnnotations() {
    annotationMapper.unloadAnnotations(annotationUI.savedAnnotations());
  }
```

Where `savedAnnotations()` is a function that returns all annotations currently loaded that have an ID.

**Comment by robertknight** [comment] 2016-09-15 15:08
I can reproduce this issue in Chrome 54.0.2816.0 but not Firefox Nightly (v51.a1)

**Comment by robertknight** [comment] 2016-09-28 16:55
Error reported above is the same as #73  and #124

**Comment by robertknight** [comment] 2016-10-14 08:14
An error occurs when serializing the range to each type of selector in `describe()` in `annotator/anchoring/html.coffee` but this error gets swallowed and the result is a new annotation with no associated selectors. This is why the annotation turns into a Page Note after saving.

```
Error describing range with type RangeAnchor(root, range) {
    if (root == null) {
      missingParameter('root');
    }
    if (range == null) {
      missingParameter('range');
    }
    this.root = root;
    this.range =… TypeError: Cannot read property 'nodeType' of undefined
    at Object.Util.getLastTextNodeUpTo (http://localhost:5000/assets/client/scripts/injector.bundle.js?06fae6:4042:14)
    at BrowserRange.Range.BrowserRange.BrowserRange.normalize (http://localhost:5000/assets/client/scripts/injector.bundle.js?06fae6:4455:24)
    at new RangeAnchor (http://localhost:5000/assets/client/scripts/injector.bundle.js?06fae6:724:42)
    at Function.RangeAnchor.fromRange (http://localhost:5000/assets/client/scripts/injector.bundle.js?06fae6:728:12)
    at http://localhost:5000/assets/client/scripts/injector.bundle.js?06fae6:370:23
    at Object.exports.describe (http://localhost:5000/assets/client/scripts/injector.bundle.js?06fae6:379:5)
    at getSelectors (http://localhost:5000/assets/client/scripts/injector.bundle.js?06fae6:1409:29)
    at Array.map (native)
    at Sidebar.module.exports.Guest.createAnnotation (http://localhost:5000/assets/client/scripts/injector.bundle.js?06fae6:1433:36)
    at Sidebar.module.exports.Sidebar.createAnnotation (http://localhost:5000/assets/client/scripts/injector.bundle.js?06fae6:2947:40)
html.coffee:110 Error describing range with type TextPositionAnchor(root, start, end) {
    _classCallCheck(this, TextPositionAnchor);

    if (root === undefined) {
      throw new Error('missing required parameter "root"');
    }
    if (… TypeError: Cannot read property 'nodeType' of null
    at isText (http://localhost:5000/assets/client/scripts/injector.bundle.js?06fae6:8529:14)
    at seek (http://localhost:5000/assets/client/scripts/injector.bundle.js?06fae6:8500:14)
    at Function.fromRange (http://localhost:5000/assets/client/scripts/injector.bundle.js?06fae6:8288:50)
    at http://localhost:5000/assets/client/scripts/injector.bundle.js?06fae6:370:23
    at Object.exports.describe (http://localhost:5000/assets/client/scripts/injector.bundle.js?06fae6:379:5)
    at getSelectors (http://localhost:5000/assets/client/scripts/injector.bundle.js?06fae6:1409:29)
    at Array.map (native)
    at Sidebar.module.exports.Guest.createAnnotation (http://localhost:5000/assets/client/scripts/injector.bundle.js?06fae6:1433:36)
    at Sidebar.module.exports.Sidebar.createAnnotation (http://localhost:5000/assets/client/scripts/injector.bundle.js?06fae6:2947:40)
    at Object.onAnnotate (http://localhost:5000/assets/client/scripts/injector.bundle.js?06fae6:1062:14)
html.coffee:110 Error describing range with type TextQuoteAnchor(root, exact) {
    var context = arguments.length <= 2 || arguments[2] === undefined ? {} : arguments[2];

    _classCallCheck(this, TextQuoteAnchor);

    if (root === undefi… TypeError: Cannot read property 'nodeType' of null
    at isText (http://localhost:5000/assets/client/scripts/injector.bundle.js?06fae6:8529:14)
    at seek (http://localhost:5000/assets/client/scripts/injector.bundle.js?06fae6:8500:14)
    at Function.fromRange (http://localhost:5000/assets/client/scripts/injector.bundle.js?06fae6:8288:50)
    at Function.fromRange (http://localhost:5000/assets/client/scripts/injector.bundle.js?06fae6:8436:57)
    at http://localhost:5000/assets/client/scripts/injector.bundle.js?06fae6:370:23
    at Object.exports.describe (http://localhost:5000/assets/client/scripts/injector.bundle.js?06fae6:379:5)
    at getSelectors (http://localhost:5000/assets/client/scripts/injector.bundle.js?06fae6:1409:29)
    at Array.map (native)
    at Sidebar.module.exports.Guest.createAnnotation (http://localhost:5000/assets/client/scripts/injector.bundle.js?06fae6:1433:36)
    at Sidebar.module.exports.Sidebar.createAnnotation (http://localhost:5000/assets/client/scripts/injector.bundle.js?06fae6:2947:40)
```

**Comment by robertknight** [comment] 2016-10-14 08:44
When clicking Annotate after triple-clicking to select the current sentence, the selected range in Chrome looks like this:

**Range structure**
```
  commonAncestorContainer: <section>
  startContainer: #text ("There are...")
  startOffset: 0
  endContainer: <h3>
  endOffset: 0
```
**HTML Structure**
```
<section>
<p><span>[START]There are</span>#text</p>
<div>
  <section class="feature-heading">
    <h3>[END]<i class="feature-icon ..."></i>Notes
```

The code in `BrowserRange#normalize` attempts to ensure that the range starts and ends at a text node, such that [Text.splitText](https://developer.mozilla.org/en-US/docs/Web/API/Text/splitText) can be called on it.

If the end container is not a text node, it attempts to drill down through the children of this node, starting at `endContainer[endOffset]` and then iteratively visiting the first child of the current node, until it reaches a text node. It then sets the start of that text node as the end of the selection. In this case, the `<h3>` has no text child. A fallback code path then gets triggered which attempts to get the last text node in the subtree rooted at `endContainer[endOffset-1]`and uses the end text position of that node. Since `endOffset` is 0, there is no such node, so this logic fails.

**Comment by robertknight** [comment] 2016-10-14 08:53
For the text position anchor, there is also an assumption that the end node of the supplied range has a text node descendant, which is not the case here. The text quote anchor fails for the same reason, since it relies on the text position anchor.

```js
// #fromRange method in dom-anchor-text-position

      // Drill down to a text node if the range ends at the container boundary.
      if (endNode.nodeType !== Node.TEXT_NODE) {
        if (endOffset === endNode.childNodes.length) {
          endNode = endNode.childNodes[endOffset - 1];
          endNode = getFirstTextNode(endNode);
          endOffset = endNode.textContent.length;
        } else {
          endNode = endNode.childNodes[endOffset];
          // **Assumes that `endNode` has a text node descendant, which is
          // not the case**
          endNode = getFirstTextNode(endNode);
          endOffset = 0;
        }
      }

      var iter = (0, _nodeIteratorShim2['default'])(root, SHOW_TEXT);
      var start = (0, _domSeek2['default'])(iter, startNode);
      var end = start + (0, _domSeek2['default'])(iter, endNode);

```

**Comment by robertknight** [comment] 2016-10-14 10:12
This is fixed by the upstream changes in https://github.com/tilgovi/dom-anchor-text-position/commit/d0d11e3630588e4f8b2dbddf5cc70d38b2491677 which drastically simplify how range -> selector conversion works for text positions.

**Comment by robertknight** [comment] 2016-10-14 10:20
![](https://github.trello.services/images/mini-trello-icon.png) [Fix error capturing selectors for certain selections](https://trello.com/c/BVn6jb34/21-fix-error-capturing-selectors-for-certain-selections)

**Comment by robertknight** [comment] 2016-10-24 17:16
The cause of this error is that the new annotation, when initially created, has a range selector but no position or quote selectors.

Anchoring _always_ fails for annotations without quote selectors.

The failure to create position and quote anchors is captured by a set of test cases in https://github.com/hypothesis/client/blob/cdaf5e8fe28ee7b06530e708f0cf2f942eee26c5/h/static/scripts/annotator/anchoring/test/html-test.js#L109 . Randall has changed the way position and quote anchoring works in the latest version of the `dom-anchor-text-{position, quote}` libraries which fixed the problem when I tested briefly. The next step is to upgrade these libraries to the latest version, which always requires adapting to some API changes.

**Closed** 2016-10-28 19:20 UTC
