### ISSUE TITLE
Annotations showing up as orphaned even when anchored.

### ISSUE THREAD

**Issue by sheetaluk** [hypothesis/client#532] opened 2017-09-06 22:03 UTC
### Steps to reproduce
1. Go to https://via.hypothes.is/http:/www.ibtimes.co.uk/reading-books-watching-films-makes-you-kinder-real-life-1571434#annotations:_MOsQlpyEeaiesf9ed4wVw

### Expected behaviour
I see anchored annotations in the 'Annotations' tab and only orphaned annotations in the 'Orphaned' tab.

### Actual behaviour
I only see orphaned annotations(92 of them) and no anchored annotations even though the anchors appear to have anchored on the page.
Also, the page takes a while to load. A user said they saw an unresponsive script message, I didn't.
I also see this JS error in the console:
Uncaught TypeError: Cannot read property 'postMessage' of undefined
    at e.module.exports.e._onMessage (cdn.hypothes.is/hypothesis/1.39.0/build/scripts/app.bundle.js?5b2a64:155)
    at cdn.hypothes.is/hypothesis/1.39.0/build/scripts/app.bundle.js?5b2a64:155
    at n (cdn.hypothes.is/hypothesis/1.39.0/build/scripts/raven.bundle.js?3d4f55:9)
cdn.hypothes.is/hypothesis/1.39.0/build/scripts/injector.bundle.js?8a864f:161 looked up unknown feature overlay_highlighter
flagEnabled @ cdn.hypothes.is/hypothesis/1.39.0/build/scripts/injector.bundle.js?8a864f:161
cdn.hypothes.is/hypothesis/1.39.0/build/scripts/injector.bundle.js?8a864f:161 looked up unknown feature overlay_highlighter
flagEnabled @ cdn.hypothes.is/hypothesis/1.39.0/build/scripts/injector.bundle.js?8a864f:161

### Browser/system information
Chrome

**Comment by robertknight** [comment] 2017-09-07 05:24
This is most likely a duplicate of https://github.com/hypothesis/client/issues/527#issuecomment-326627225

**Comment by robertknight** [comment] 2017-09-11 09:45
This was indeed a duplicate of #527. See the last comments in that issue for more details.

**Closed by robertknight** 2017-09-11 09:45 UTC
