### ISSUE TITLE
client does not switch to orphans tab on new annotation

### ISSUE THREAD

**Issue by tgbugs** [hypothesis/client#504] opened 2017-07-19 19:11 UTC
### Steps to reproduce
1. On Chrome on macos highlight the doi link at the bottom of page 1 on [this pdf](http://hypothesis-local.olympiangods.org/ma2005.pdf) and hit annotate.
2. The box to edit and save the annotation does not appear.
3. There should be a new unsubmitted annotation in the orphans tab.

### Expected behaviour
When annotating to a block of text that the client cannot anchor the client should automatically switch to the orphans tab. I had a user who could not find the annotation to edit since it appeared as if the client simply didn't have it.

### Actual behaviour
Client remains on the annotations tab.

### Browser/system information
Bug was observed on macos Chrome, but the behavior should be present whenever the client cannot anchor when creating a new annotation.

### Additional details
The exact steps cannot be used to reproduced the behavior on linux  and may have to do with how macos deals with the special character in the doi (another bug?).

Here is an image of the exact text (underlined in red).
![hypothesis bug](https://user-images.githubusercontent.com/4299776/28384995-657702a0-6c7b-11e7-966e-49cb26f56c5f.png)

**Comment by klemay** [comment] 2020-09-10 19:36
Closing as I'm not able to reproduce this. 

When I highlight the DOI at the bottom of the page and click "Annotate," a draft annotation appears in the sidebar. I'm able to post my annotation just as expected:

<img width="1069" alt="Screen Shot 2020-09-10 at 3 35 31 PM" src="https://user-images.githubusercontent.com/12087705/92792182-51601600-f37b-11ea-8ddb-c719cd9d6ad8.png">

**Closed by klemay** 2020-09-10 19:36 UTC
