### ISSUE TITLE
Unusual animation of buckets on touch devices 

### ISSUE THREAD

**Issue by esanzgar** [hypothesis/client#2813] opened 2020-12-10 14:31 UTC
### Steps to reproduce
1. On a touch device, go to https://via.hypothes.is/https://example.com
2. Open the sidebar
3. Touch the first annotation card

### Expected behaviour
Touching the first annotation card should not trigger any animation in the bucket bar

### Actual behaviour
An animation is trigger. The first and last state on the animation are the same, so the animation is pointless:

![ezgif com-gif-maker](https://user-images.githubusercontent.com/8555781/101785059-99b6dd80-3afc-11eb-8243-0113f55bfe62.gif)

### Browser/system information
All touch devices (Android and iOS tested)

**Comment by robertknight** [comment] 2023-09-22 13:55
I can't reproduce any more. We've rewritten the bucket bar positioning code since the issue was filed, so it isn't surprising if this got fixed in the process.

**Closed by robertknight** 2023-09-22 13:55 UTC
Labels: bug
