### ISSUE TITLE
Annotation/Highlight Button does not appear

### ISSUE THREAD

**Issue by heatherstaines** [hypothesis/client#269] opened 2017-03-04 18:53 UTC
### Steps to reproduce
1.Trying to annotate article: http://www.flyertalk.com/articles/cbp-agents-demand-id-before-domestic-passengers-allowed-to-disembark-at-jfk.html?utm_medium=Email&utm_campaign=
2.Hypothesis opens but when I select text no annotation/highlight button appears
3. Doesn't make a difference if the sidebar is open or closed....

### Expected behaviour
Tell us what should happen.
Highlighting content should make the annotation/highlight button appear.

### Actual behaviour
Tell us what happens instead.
Text can be selected, but no button appears.

### Browser/system information
Tell us which browser, browser version, and operating system you were using when
you encountered this issue.
Tried on Chrome 56.0.2924.87
Tried on Firefox 51.0.1 
Sierra 10.12.3

### Additional details
If you have other information which might be helpful, please include it. If a
screenshot will help to illustrate the issue you are reporting, please include
one.

**Comment by sean-roberts** [comment] 2017-03-13 16:25
This problem is caused by the notorious Z-index issue.

This site has a `#post-social-out` element with z-index of 2500 while the current adder z-index is still 999

**Comment by sean-roberts** [comment] 2017-03-13 16:27
fix is tracked and discussed here: #256

**Comment by klemay** [comment] 2019-02-04 16:19
Closing in favor of #256

**Closed by klemay** 2019-02-04 16:19 UTC
Labels: Website Environment Conflict
