### ISSUE TITLE
Cannot doubleclick to select text after line breaks in PDFs (Chrome only)

### ISSUE THREAD

**Issue by dwhly** [hypothesis/client#54] opened 2016-07-26 22:04 UTC
### Steps to reproduce
1. In Chrome, open a PDF like this one: http://docdrop.org/pdf/Bullets-rEMN9.pdf/
2. Doubleclick to select the first word in a paragraph after a line break, or a bulleted list
3. Click Annotate
### Expected behaviour

The sidebar should open
### Actual behaviour

It does not.

The console reports the following error:
hypothes.is/assets/client/scripts/injector.bundle.js?5c352c:595 Uncaught TypeError: Cannot read property 'classList' of nullgetNodeTextLayer @ hypothes.is/assets/client/scripts/injector.bundle.js?5c352c:595exports.describe @ hypothes.is/assets/client/scripts/injector.bundle.js?5c352c:846getSelectors @ hypothes.is/assets/client/scripts/injector.bundle.js?5c352c:1431module.exports.Guest.createAnnotation @ hypothes.is/assets/client/scripts/injector.bundle.js?5c352c:1455module.exports.Sidebar.createAnnotation @ hypothes.is/assets/client/scripts/injector.bundle.js?5c352c:2975module.exports.Guest.onAdderClick @ hypothes.is/assets/client/scripts/injector.bundle.js?5c352c:1658(anonymous function) @ hypothes.is/assets/client/scripts/injector.bundle.js?5c352c:3878closure @ hypothes.is/assets/client/scripts/injector.bundle.js?5c352c:4268dispatch @ hypothes.is/assets/client/scripts/jquery.bundle.js?aa4179:4642elemData.handle @ hypothes.is/assets/client/scripts/jquery.bundle.js?aa4179:4310
### Browser/system information

Chrome
### Additional details

I believe this may have been previously reported, but I cannot find the bug.

**Comment by dwhly** [comment] 2016-07-26 22:13
Actually, the problem is worse than I first reported.  It's actually a bug annotating the first word of *any* new block of text, including beginnings of lines after paragraph breaks as well as bulleted lists.

Thus as it stands, you cannot have an annotation which includes the first word of any paragraph.

**Comment by dwhly** [comment] 2016-07-26 22:21
Ok-- It's only doubleclicking to select a first word after a break, and only in Chrome.  Added Console output.

**Comment by seanh** [comment] 2016-07-29 13:57
I can reproduce this

**Comment by seanh** [comment] 2016-07-29 14:05
`pdf.coffee:21 Uncaught TypeError: Cannot read property 'classList' of null` in `pdf.coffee` line 21

**Comment by lyzadanger** [comment] 2020-10-27 18:39
Dear @dwhly and @seanh — I am not able to reproduce this issue in Chrome 86 on MacOS; I tried on multiple PDFs. The code referenced in Dan's original console output has been rewritten since. I believe this issue is no longer valid, but wanted to ping you both before closing it just in case.

(I am able to annotate the first word after a line break in a PDF via double-click just fine at this time).

**Closed** 2020-11-09 19:49 UTC
Labels: PDF, Unable to reproduce
