### ISSUE TITLE
Sidebar obscures annotate popup

### ISSUE THREAD

**Issue by seanh** [hypothesis/client#463] opened 2017-06-23 16:52 UTC
When the sidebar partially covers the page content, then when your selection includes some of the covered content the sidebar can end up partially or entirely obscuring the `Annotate | Highlight` popup:

![peek 2017-06-23 17-50](https://user-images.githubusercontent.com/22498/27492011-80e53c76-583c-11e7-9a69-7cfbfca04b38.gif)

**Comment by robertknight** [comment] 2021-03-18 11:58
I confirmed that this issue still applies with the latest version of the client (1.713.0). We assign a ridiculous z-index value to the sidebar to make sure that no page content appears on top of it. This has the effect of making it appear above the adder as well.

**Comment by esanzgar** [comment] 2021-03-18 12:28
A text selection should trigger the closing of the sidebar. However, some selections where the cursor ends on top of the sidebar doesn't trigger the collapsing of the sidebar.

**Comment by esanzgar** [comment] 2021-03-18 15:33
Looking at the screenshot form @seanh I notice that half of the `adder` should be visible because it is not covered by the sidebar. This looks more an event issue of some sort.

**Closed** 2021-03-30 11:28 UTC
