### ISSUE TITLE
Click to scroll annotation bodies doesn't work properly on pdf2htmlEX

### ISSUE THREAD

**Issue by dwhly** [hypothesis/client#433] opened 2017-06-08 15:21 UTC
### Steps to reproduce
1. Go here: https://via.hypothes.is/http://coolwanglu.github.io/pdf2htmlEX/doc/tb108wang.html
2. Scroll document to bottom of last page.
3. Open sidebar, click last annotation by judell.

### Expected behaviour
Document should scroll to selection of that annotation

### Actual behaviour
Document scrolls up a bit, but requires subsequent clicks on the same annotation to bring it up to the right place.

### Browser/system information
Via in Chrome

**Comment by robertknight** [comment] 2017-06-08 15:47
I had a quick look at this. The issue is that pages which are scrolled out of view get hidden, so the client cannot scroll to it. The reason that the client scrolls at all I believe is because it tries to scroll to the "top" coordinate of the highlight element which is 0 (since the top/left/width/height coordinates of hidden elements are all zero).

In order to resolve this, we'll need some specific integration with the pdf2htmlEX viewer, similar to what we did with PDF.js.

**Comment by robertknight** [comment] 2018-02-28 11:08
Closing this in favour of https://github.com/hypothesis/product-backlog/issues/503

**Closed by robertknight** 2018-02-28 11:08 UTC
