### ISSUE TITLE
Search results do not filter anchors / highlights.

### ISSUE THREAD

**Issue by greebie** [hypothesis/client#217] opened 2017-02-08 17:07 UTC
### Steps to reproduce
1. Open Client and press search feature.
2. Conduct a search for user: username (or any search

### Expected behaviour
 For improved experience it would be nice to hide/filter out the anchors / highlights in the main page as well.

### Actual behaviour
Currently the search feature only filters annotations in the sidebar.

### Browser/system information
(This feature was discussed previously in the newsgroup in the following thread:

https://groups.google.com/a/list.hypothes.is/forum/?utm_medium=email&utm_source=footer#!msg/dev/MjEs9U0mITs/24xDMvLhCgAJ

### Additional details

Pull request may follow, as I will be working on this behavior in the short run.

**Comment by lyzadanger** [comment] 2020-09-11 13:14
This is a dupe of #1245

**Closed by lyzadanger** 2020-09-11 13:14 UTC
