### ISSUE TITLE
Multiple annotations by the same person have the same accessible title

### ISSUE THREAD

**Issue by acelaya** [hypothesis/client#6305] opened 2024-04-02 09:43 UTC
This results in duplicate headings which may make it challenging to identify which annotation is which or to navigate by heading.

Some things we could use to improve this:

* The timestamp the annotation was created (easiest, most universal)
* The first few words of the quote (if present, not available for page notes)
* The PDF page number (if present)

**Comment by robertknight** [comment] 2024-04-22 13:26
This is a duplicate of https://github.com/hypothesis/client/issues/6305. That issue has the original feedback from the accessibility audit in it, so I will leave it open.

**Closed by robertknight** 2024-04-22 13:26 UTC
Labels: accessibility

**Comment by acelaya** [comment] 2024-04-24 08:22
> > This is a duplicate of #6305. That issue has the original feedback from the accessibility audit in it, so I will leave it open.
> 
> This is #6305 lol. Lather. Rinse. Repeat.

Technically speaking, the comment is correct 😅
