### ISSUE TITLE
can't log in at Edge add-on

### ISSUE THREAD

**Issue by luvletter93** [hypothesis/client#6292] opened 2024-03-29 07:09 UTC
![temp](https://github.com/hypothesis/product-backlog/assets/108335357/6a744255-abe7-435c-a727-1ef0623498e1)
when I click the "log in" button, the new log in window will open and disappear after several seconds. is it out of service?

**Comment by robertknight** [comment] 2024-04-19 14:51
> when I click the "log in" button, the new log in window will open and disappear after several seconds. is it out of service?

Does the window disappear entirely or remain present, but blank, as in your screenshot? If the issue is indeed https://github.com/hypothesis/client/issues/5769 then the window will remain present, but blank, after logging in.

Can you provide the URL of a website you were trying to annotate when you see this happen?

**Comment by luvletter93** [comment] 2024-05-30 14:29
Yes, the popup windows disappears entirely, and didn't remain present. And this problem will show in any website that i'm trying to annotate will happens. Plus, i use "hypotheses" on the Edge brower, and I downloaded it from Edge's official addons website.(https://microsoftedge.microsoft.com/addons) Since the core of Edge brower is chrome, I hope hypothesis can work on Edge.&nbsp; I made a video to show this problem.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hypothesis/client"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月19日(星期五) 晚上10:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hypothesis/client] can't log in at Edge add-on (Issue #6292)





  
when I click the "log in" button, the new log in window will open and disappear after several seconds. is it out of service?
  
Does the popup window disappear entirely or remain present, but blank, as in your screenshot? If the issue is indeed #5769 then the window will remain present, but blank, after logging in.
 
Can you provide the URL of a website you were trying to annotate when you see this happen?

**Comment by acelaya** [comment] 2024-05-30 14:43
> Plus, i use "hypotheses" on the Edge brower, and I downloaded it from Edge's official addons website.(https://microsoftedge.microsoft.com/addons)

I guess you are talking about [this one](https://microsoftedge.microsoft.com/addons/detail/hypothesis-web-pdf-an/dfimadcnljbenipfkcpplpncpnhbmban)? Just FYI, but we don't publish the web extension in the MS Edge store. That seems to  be something someone has published on their own. It's not an extension we officially support.

The first problem I can see there is that it has not been updated for at least one year, so it can potentially fail due to how it deviates with other pieces of the ecosystem.

We'll probably need to investigate this further.

**Comment by luvletter93** [comment] 2024-06-04 06:20
Yes. the addons in the microsoft edge store is not updated. When i tried to downloaded the latest version from chrome store, problem solved. So the latest version can be used in Edge since the core of Edge brower is chromium. If you could publish hypothesis.is to MS Edge store, it will solve many people's problems. Thanks for   solving my problem!

**Comment by acelaya** [comment] 2024-06-14 09:46
Closing this as resolved for now. We'll have to think how to proceed regarding that unofficial extension.

**Closed by acelaya** 2024-06-14 09:46 UTC
