### ISSUE TITLE
Highlighted region in PDF is offset from initial selection

### ISSUE THREAD

**Issue by wwj718** [hypothesis/client#381] opened 2017-05-11 13:40 UTC
_Updated 2018-12-14 with detailed steps to reproduce._

**Original report (wwj718)**

when I  use the client to  annotate some pdf file . the highlighted region may be offset

for example:

![image](https://cloud.githubusercontent.com/assets/3153878/25951985/f8eef9d6-3691-11e7-854d-dd5817355fed.png)

----

**Updated report (robertknight)**

When selecting text and clicking the Highlight or Annotate buttons, the resulting highlight is sometimes offset from the initial selection, although the text quote shown in the annotation card is correct.

**Steps to reproduce**

1. Open [this PDF](https://arxiv.org/pdf/1512.02325.pdf) and activate the Hypothesis Chrome extension, or paste the link into Via.
2. Scroll to the page numbered 6 in the original PDF and highlight the text "6 default boxes per feature map location"
3. Click "Highlight"

**Expected result:** The originally selected text is highlighted.
**Actual result:** Text offset from the original is highlighted.

**Notes**

The highlight, with the wrong text (should start at the digit "6") highlighted:

<img width="946" alt="highlight output" src="https://user-images.githubusercontent.com/2458/50001165-eca03d80-ff93-11e8-9b38-bbcd759e22f4.png">

The local DOM in the PDF.js text layer after highlighting:

<img width="746" alt="dom after highlighting" src="https://user-images.githubusercontent.com/2458/50001171-f1fd8800-ff93-11e8-832f-df0cee9fd7ca.png">

Annotation card, showing the correct text quote:

<img width="422" alt="annotation card" src="https://user-images.githubusercontent.com/2458/50001180-f75ad280-ff93-11e8-9ddb-6d60122a736e.png">

**Comment by robertknight** [comment] 2017-05-11 13:53
Thank-you for the report! I can reproduce the problem in Chrome v58 using the v1.15 of the extension. See this annotation: https://hyp.is/2BMeXjZQEeeu3bfUV70Dhw/cn.arxiv.org/pdf/1705.03122

When the text is initially selected, the correct region of the page is highlighted in the selection color:

<img width="445" alt="screenshot 2017-05-11 14 50 45" src="https://cloud.githubusercontent.com/assets/2458/25952744/6915e44c-3659-11e7-902e-76b5cd7b93fe.png">

When a highlight or annotation is created, the highlight is offset as in the image in the description.

**Comment by wwj718** [comment] 2017-05-11 14:00
👍

**Comment by klemay** [comment] 2018-07-25 19:05
Closing in favor of https://github.com/hypothesis/product-backlog/issues/740, where PDF issues have been compiled.

**Comment by robertknight** [comment] 2018-12-14 11:39
Hi @klemay, I've added specific steps to reproduce this issue and am going to re-open, as this is a specific bug in the client which can be worked on, as opposed to https://github.com/hypothesis/product-backlog/issues/740 which I gather is about producing guidance for how people can author PDFs to work best with Hypothesis.

In this case the PDFs I've been annotating recently where I've seen this issue come from an existing website (https://arxiv.org) and were created born-digital, rather than having been digitised specifically for Hypothesis (eg. via OCR). From what I can see looking at the text layer in the PDF, there is nothing in the PDF itself which makes getting the highlighting right inherently difficult.

**Comment by judell** [comment] 2019-02-08 17:45
If I'm understanding this correctly, it does not now reproduce in the current extension or in Firefox with PDF.js 2.

![image](https://user-images.githubusercontent.com/46509/52495621-2c476800-2b86-11e9-94a4-d7b71b4bb139.png)

https://hyp.is/ti4FyCvIEemm0bf2aqj81g/arxiv.org/pdf/1512.02325.pdf

@klemay if you can confirm, we can close this one.

**Comment by klemay** [comment] 2019-02-08 17:54
@judell yep, I'm unable to reproduce now!

**Closed** 2020-09-10 19:38 UTC
Labels: PDF
