### ISSUE TITLE
Missing mock in component test causes multitudes of tests to fail across app

### ISSUE THREAD

**Issue by lyzadanger** [hypothesis/client#1788] opened 2020-02-13 16:42 UTC
I've noticed this for a while, but failed to report it until now. If one makes changes to a component such that there is a new injected prop or method unaccounted for in test mocks for that component, it often causes a cascade of test fails across the app. It's typically the same tests that fail—all of the failing tests seem to have a component of time/re-render, e.g. they use `wrapper.update()` or `setProps`. I haven't looked much deeper than that.

The full error output exceeds scrollback in my terminal and is very long; here's a sampling of the end part of it. In the case here, I updated a component to use the `profile()` method on `store` (it already had other `store` methods mocked, but the tests had not been updated to mock `profile).

Once I mock `store.profile()` in the component's tests, these failures are fixed.

```
      ✖ closes the suggestions when deleting <input> value
        HeadlessChrome 80.0.3987 (Mac OS X 10.14.6)
      AssertionError: expected 0 to equal 2

      + expected - actual

      -0
      +2

    at Context.<anonymous> (/var/folders/mj/qscc6y2j34sc37g5nx461_qr0000gn/T/sidebar/components/test/tag-editor-test.js:131:14 <- /var/folders/mj/qscc6y2j34sc37g5nx461_qr0000gn/T/5874c561727049be7878e756603d613d.browserify.js:295268:14)


      ✖ does not close the suggestions when deleting only part of the <input> value
        HeadlessChrome 80.0.3987 (Mac OS X 10.14.6)
      AssertionError: expected 0 to equal 2

      + expected - actual

      -0
      +2

    at Context.<anonymous> (/var/folders/mj/qscc6y2j34sc37g5nx461_qr0000gn/T/sidebar/components/test/tag-editor-test.js:145:14 <- /var/folders/mj/qscc6y2j34sc37g5nx461_qr0000gn/T/5874c561727049be7878e756603d613d.browserify.js:295282:14)


      ✖ opens the suggestions on focus if <input> is not empty
        HeadlessChrome 80.0.3987 (Mac OS X 10.14.6)
      AssertionError: expected false to equal true

      + expected - actual

      -false
      +true

    at Context.<anonymous> (/var/folders/mj/qscc6y2j34sc37g5nx461_qr0000gn/T/sidebar/components/test/tag-editor-test.js:159:14 <- /var/folders/mj/qscc6y2j34sc37g5nx461_qr0000gn/T/5874c561727049be7878e756603d613d.browserify.js:295296:14)


      ✖ closes the suggestions when focus is removed from the <input> field
        HeadlessChrome 80.0.3987 (Mac OS X 10.14.6)
      AssertionError: expected false to equal true

      + expected - actual

      -false
      +true

    at Context.<anonymous> (/var/folders/mj/qscc6y2j34sc37g5nx461_qr0000gn/T/sidebar/components/test/tag-editor-test.js:179:14 <- /var/folders/mj/qscc6y2j34sc37g5nx461_qr0000gn/T/5874c561727049be7878e756603d613d.browserify.js:295313:14)


      ✖ does not render duplicate suggestions
        HeadlessChrome 80.0.3987 (Mac OS X 10.14.6)
      AssertionError: expected [] to deeply equal [ 'tag4' ]

      + expected - actual

      -[]
      +[
      +  "tag4"
      +]

    at Context.<anonymous> (/var/folders/mj/qscc6y2j34sc37g5nx461_qr0000gn/T/sidebar/components/test/tag-editor-test.js:194:14 <- /var/folders/mj/qscc6y2j34sc37g5nx461_qr0000gn/T/5874c561727049be7878e756603d613d.browserify.js:295327:14)


    when adding tags
      ✖ adds a tag from the suggestions list
        HeadlessChrome 80.0.3987 (Mac OS X 10.14.6)
      AssertionError: expected false to be true

      + expected - actual

      -false
      +true

    at assertAddTagsSuccess (/var/folders/mj/qscc6y2j34sc37g5nx461_qr0000gn/T/sidebar/components/test/tag-editor-test.js:204:14 <- /var/folders/mj/qscc6y2j34sc37g5nx461_qr0000gn/T/5874c561727049be7878e756603d613d.browserify.js:295336:14)
    at Context.<anonymous> (/var/folders/mj/qscc6y2j34sc37g5nx461_qr0000gn/T/sidebar/components/test/tag-editor-test.js:253:7 <- /var/folders/mj/qscc6y2j34sc37g5nx461_qr0000gn/T/5874c561727049be7878e756603d613d.browserify.js:295388:7)


    navigating suggestions via keyboard
      ✖ should set the initial `activeItem` value to -1 when opening suggestions
        HeadlessChrome 80.0.3987 (Mac OS X 10.14.6)
      AssertionError: expected false to equal true

      + expected - actual

      -false
      +true

    at Context.<anonymous> (/var/folders/mj/qscc6y2j34sc37g5nx461_qr0000gn/T/sidebar/components/test/tag-editor-test.js:306:14 <- /var/folders/mj/qscc6y2j34sc37g5nx461_qr0000gn/T/5874c561727049be7878e756603d613d.browserify.js:295437:14)


      ✖ should increment the `activeItem` when pressing down circularly
        HeadlessChrome 80.0.3987 (Mac OS X 10.14.6)
      AssertionError: expected -1 to equal 0

      + expected - actual

      --1
      +0

    at Context.<anonymous> (/var/folders/mj/qscc6y2j34sc37g5nx461_qr0000gn/T/sidebar/components/test/tag-editor-test.js:315:14 <- /var/folders/mj/qscc6y2j34sc37g5nx461_qr0000gn/T/5874c561727049be7878e756603d613d.browserify.js:295446:14)


      ✖ should decrement the `activeItem` when pressing up circularly
        HeadlessChrome 80.0.3987 (Mac OS X 10.14.6)
      AssertionError: expected -1 to equal 1

      + expected - actual

      --1
      +1

    at Context.<anonymous> (/var/folders/mj/qscc6y2j34sc37g5nx461_qr0000gn/T/sidebar/components/test/tag-editor-test.js:329:14 <- /var/folders/mj/qscc6y2j34sc37g5nx461_qr0000gn/T/5874c561727049be7878e756603d613d.browserify.js:295459:14)


      ✖ should set `activeItem` to -1 when clearing the suggestions
        HeadlessChrome 80.0.3987 (Mac OS X 10.14.6)
      AssertionError: expected -1 to equal 0

      + expected - actual

      --1
      +0

    at Context.<anonymous> (/var/folders/mj/qscc6y2j34sc37g5nx461_qr0000gn/T/sidebar/components/test/tag-editor-test.js:342:14 <- /var/folders/mj/qscc6y2j34sc37g5nx461_qr0000gn/T/5874c561727049be7878e756603d613d.browserify.js:295471:14)


    accessibility attributes and ids
      ✖ sets `aria-expanded` value to match open state
        HeadlessChrome 80.0.3987 (Mac OS X 10.14.6)
      AssertionError: expected 'false' to equal 'true'

      + expected - actual

      -false
      +true

    at Context.<anonymous> (/var/folders/mj/qscc6y2j34sc37g5nx461_qr0000gn/T/sidebar/components/test/tag-editor-test.js:374:14 <- /var/folders/mj/qscc6y2j34sc37g5nx461_qr0000gn/T/5874c561727049be7878e756603d613d.browserify.js:295494:14)


      ✖ sets the <AutocompleteList> `activeItem` prop to match the selected item index
        HeadlessChrome 80.0.3987 (Mac OS X 10.14.6)
      AssertionError: expected undefined to equal -1

      + expected - actual

      -[undefined]
      +-1

    at checkAttributes (/var/folders/mj/qscc6y2j34sc37g5nx461_qr0000gn/T/sidebar/components/test/tag-editor-test.js:395:16 <- /var/folders/mj/qscc6y2j34sc37g5nx461_qr0000gn/T/5874c561727049be7878e756603d613d.browserify.js:295504:16)
    at Context.<anonymous> (/var/folders/mj/qscc6y2j34sc37g5nx461_qr0000gn/T/sidebar/components/test/tag-editor-test.js:408:7 <- /var/folders/mj/qscc6y2j34sc37g5nx461_qr0000gn/T/5874c561727049be7878e756603d613d.browserify.js:295515:7)


  Timestamp
    timestamp label
      ✖ is updated after time passes
        HeadlessChrome 80.0.3987 (Mac OS X 10.14.6)
      AssertionError: expected 'a while ago' to equal '60 jiffies'

      + expected - actual

      -a while ago
      +60 jiffies

    at Context.<anonymous> (/var/folders/mj/qscc6y2j34sc37g5nx461_qr0000gn/T/sidebar/components/test/timestamp-test.js:82:14 <- /var/folders/mj/qscc6y2j34sc37g5nx461_qr0000gn/T/5874c561727049be7878e756603d613d.browserify.js:296028:14)


      ✖ is no longer updated after the component is destroyed
        HeadlessChrome 80.0.3987 (Mac OS X 10.14.6)
      AssertError: expected stub to have been called at least once but was never called
          at Function.fail (/Users/lyza/Projects/h-client/node_modules/sinon/pkg/sinon.js:155:21)
          at failAssertion (/Users/lyza/Projects/h-client/node_modules/sinon/pkg/sinon.js:114:16)
          at Function.assert.<computed> [as called] (/Users/lyza/Projects/h-client/node_modules/sinon/pkg/sinon.js:140:13)
          at Context.<anonymous> (/var/folders/mj/qscc6y2j34sc37g5nx461_qr0000gn/T/sidebar/components/test/timestamp-test.js:92:14 <- /var/folders/mj/qscc6y2j34sc37g5nx461_qr0000gn/T/5874c561727049be7878e756603d613d.browserify.js:296035:14)

  useStore
    ✖ re-renders when the store changes and result of `callback(store)` also changes
      HeadlessChrome 80.0.3987 (Mac OS X 10.14.6)
    AssertionError: expected '10' to equal '11'

      + expected - actual

      -10
      +11

    at Context.<anonymous> (/var/folders/mj/qscc6y2j34sc37g5nx461_qr0000gn/T/sidebar/store/test/use-store-test.js:58:12 <- /var/folders/mj/qscc6y2j34sc37g5nx461_qr0000gn/T/5874c561727049be7878e756603d613d.browserify.js:369728:12)


    ✖ unsubscribes when the component is unmounted
      HeadlessChrome 80.0.3987 (Mac OS X 10.14.6)
    AssertError: expected stub to be called once but was called 0 times
        at Function.fail (/Users/lyza/Projects/h-client/node_modules/sinon/pkg/sinon.js:155:21)
        at failAssertion (/Users/lyza/Projects/h-client/node_modules/sinon/pkg/sinon.js:114:16)
        at Function.assert.<computed> [as calledOnce] (/Users/lyza/Projects/h-client/node_modules/sinon/pkg/sinon.js:140:13)
        at Context.<anonymous> (/var/folders/mj/qscc6y2j34sc37g5nx461_qr0000gn/T/sidebar/store/test/use-store-test.js:101:12 <- /var/folders/mj/qscc6y2j34sc37g5nx461_qr0000gn/T/5874c561727049be7878e756603d613d.browserify.js:369776:12)

TOTAL: 84 FAILED, 2082 SUCCESS
```

**Comment by robertknight** [comment] 2024-10-23 12:40
I'm closing the issue for the moment because it hasn't been a pain point that I've run into recently. It probably is still valid, but I think we'd need specific steps to reproduce for a specific test.

**Closed by robertknight** 2024-10-23 12:40 UTC
Labels: technical debt
