### ISSUE TITLE
Hindawi pages scroll to end on annotation focus.

### ISSUE THREAD

**Issue by heatherstaines** [hypothesis/client#600] opened 2017-11-21 17:03 UTC
### Steps to reproduce
1. I am using Chrome with the browser extension.
2. Making an annotation on Hindawi Content: https://www.hindawi.com/archive/2014/716053/
3. After I make an annotation the article page scrolls to the bottom. (I tried this on multiple articles and the behavior has been reproduced at Hindawi and by Dan.) Clicking on the card does not make the page scroll back to annotation.

### Expected behaviour
Tell us what should happen.
Annotation card should stay close to the annotation and not scroll. Clicking on the card should return user to near the annotation.

### Actual behaviour
Tell us what happens instead.
After the annotation is posted, the article scrolls to the bottom.

### Browser/system information
Tell us which browser, browser version, and operating system you were using when
you encountered this issue.
Chrome Version 62.0.3202.94 (Official Build) (64-bit)

### Additional details
If you have other information which might be helpful, please include it. If a
screenshot will help to illustrate the issue you are reporting, please include
one.

**Comment by robertknight** [comment] 2019-02-14 12:25
I can confirm this issue still exists with Hypothesis v1.140.0.

**Comment by lyzadanger** [comment] 2020-09-11 12:43
@klemay The original URL provided for this issue is a 404. Can you help me track down if this is still an issue?

**Comment by klemay** [comment] 2020-09-11 20:02
@lyzadanger I tried to annotate on a few pages at hindawi.com and did not experience what's described here - looks like Hindawi may have redesigned their site since this was opened. Closing the issue.

**Closed by klemay** 2020-09-11 20:02 UTC
Labels: Needs reproduction, Specific to URL/Site
