### ISSUE TITLE
Web client crashing Chrome frequently when adding tags

### ISSUE THREAD

**Issue by chrisaldrich** [hypothesis/client#1689] opened 2020-01-15 17:26 UTC
I'm currently using Chrome Version 79.0.3945.117 (Official Build) (64-bit) via the chrome extension on Windows 10 (v1809) and I'm noticing just within the last two weeks that as I'm typing within the H interface that Chrome suddenly crashes.

All of the crashes have occurred as I'm adding one or more tags to an annotation/highlight. I haven't experienced a crash while creating annotation text. 

The crash is immediate and complete and doesn't just take out the individual tab, but the entirety of the Chrome processes. While it's possible that this could be a Chrome issue, I've not experienced any crashes with any other websites in ages. I also know that there has been some new code and UI work around the interface and the way that tags are displayed in the public H product.

My initial guess is that something may be happening within the memory/caching as H tries to pull past tags from the server to guess what I'm typing. 

I've alternated with using Firefox and the bookmarklet and have yet to see an issue with crashes there.

(Originally published at: https://boffosocko.com/2020/01/15/web-client-crashing-chrome-frequently-when-adding-tags/)

**Comment by robertknight** [comment] 2020-01-17 16:38
@chrisaldrich - Can you confirm what version of the Hypothesis extension you have installed? You can find out by clicking the help ("?") icon at the top of the Hypothesis annotation pane and selecting "About this version".

**Comment by LMS007** [comment] 2020-01-17 16:39
@TylerRick if you have saved those local tags ( the map and the list) and you feel comfortable sharing them  here, then that could help us understand how to replicate this issue or if it's related to the data at all. Or if you don't want to paste them here, you could send them to support@hypothes.is and just reference this ticket.

Thank you

**Comment by TylerRick** [comment] 2020-01-17 20:18
@LMS007 Yes, I saved the local tags. I actually only saved the map because it looked like the list could be trivially derived from the map (`Object.keys(map)`).

I wouldn't _think_ that there's anything special about my data that would contribute to reproducing this behavior, but I'm happy to share it with you if you think it could help. I sent it as an attachment to support@hypothes.is. It should be attached to ticket #7901 in Zendesk.

I haven't yet been able to reproduce since putting my tags back in `localStorage`, but I'll post back again if I'm able to again.

That seems to be the main challenge with this issue — how to consistently reproduce it.

Thanks for trying to get this figured out.

**Comment by LMS007** [comment] 2020-01-21 00:59
Thank you Tyler, I was also unable to reproduce it with your tag set but worth trying! I'll keep looking for a root cause. I'm glad you saved your tags and that is interesting they are working again.

**Comment by chrisaldrich** [comment] 2020-01-30 04:20
Apologies for the delay, I've cleared out the caches as @judell indicated and haven't seen any issues for the last few days. I had a large number of tags, though I don't think the number was as large as @TylerRick's. 

I feel like @TylerRick has done an excellent job of discussing the pros/cons of the user facing issues and concerns. I'm glad to know that this is where these reside so I can fix misspellings and can change the local cache to better match some of my personal website's pre-existing taxonomies so that there is a 1-1 onto mapping of my Hypothesis tags and those on my site (or at least for the top 20% of most commonly used tags) for syndicating content more easily.

For the record, and for @robertknight's query, below is my version information:
`account: Chris Aldrich (acct:chrisaldrich@hypothes.is)`
`userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko)`
`Chrome/79.0.3945.130 Safari/537.36`
`version: 1.272.0`

My recollection of the crashes is that they were typically on tags that began with the letters `in`, though there were one or two instances with other short tag fragments. Almost all my data is public facing, so viewing my tags on the public instance might be illustrative.

Perhaps it's spurious, but @TylerRick and I are both sitting around the 2,000 annotation mark and may be at the upper end of the bell curve of users. Jon (~5,300) and Jeremy (~3,600) are the only people I'm aware of with more. user:esperluette may be an interesting test case given the high number of their tags that begin with the `hw-` combination.

**Comment by robertknight** [comment] 2021-03-18 11:44
The screenshot in https://github.com/hypothesis/client/issues/1689#issuecomment-575269754 seems to show that the issue was related to our attempt to use a native `<datalist>` element, which we no longer do. I'm going to close the issue on that basis, but please respond if you still see it.

**Closed by robertknight** 2021-03-18 11:44 UTC
