### ISSUE TITLE
Tag is silently ignored if it is not explicitly confirmed (by comma or click on suggestion)

### ISSUE THREAD

**Issue by blipp** [hypothesis/client#2100] opened 2020-04-29 11:39 UTC
### Steps to reproduce
1. Select some text to create a new annotation.
2. Enter some text into the text field for the annotation.
3. Start typing a tag in the text field for tags.
4. Do _not_ press the comma key, and do _not_ click on any suggested tag, if there are any suggestions being displayed in a drop down.
5. Click on “Post to Public” or “Post to Only Me” to save the annotation. If the suggested tags drop down is hiding the button, first click somewhere else in the client's sidebar to let the suggested tags drop down disappear.

### Expected behaviour
The client should either add the unconfirmed tag, or even better, notify the user that there is unconfirmed text in the tag text field and ask if this unconfirmed tag should be added or if the user wants to abort the posting process to again work on the tags.

### Actual behaviour
The unconfirmed tag is not added to the annotation and there is no notification to the user about that.

### Browser/system information
Ubuntu 19.10, Firefox 75.0

### Additional details
Screenshot: The tag “Test” has not been confirmed (e.g. by pressing comma), but the text “Test” is still present in the tag text field:
![Screenshot from 2020-04-29 13-27-55](https://user-images.githubusercontent.com/138279/80591206-919ea780-8a1d-11ea-808c-86647661abcc.png)

Screenshot: The annotation has been saved, without the tag “Test” being added
![Screenshot from 2020-04-29 13-28-05](https://user-images.githubusercontent.com/138279/80591204-91061100-8a1d-11ea-81b2-7a2419ec7662.png)

**Comment by LMS007** [comment] 2020-05-04 15:19
Thanks @blipp 

duplicate of https://github.com/hypothesis/client/issues/1954

**Closed by LMS007** 2020-05-04 15:19 UTC
