### ISSUE TITLE
Annotations that don't anchor HTML <> PDF

### ISSUE THREAD

**Issue by dwhly** [hypothesis/client#471] opened 2017-06-27 18:55 UTC
### Examples
This will provide a set of links to examples of annotations that don't reliably anchor between the HTML and PDF versions of an article.  These might be helpful at we look at adjustments to the underlying algorithm.

https://hyp.is/pY-BBlqCEeefuSMmrTNmGg/nn.neurology.org/content/4/4/e353.full
Orphans here: http://nn.neurology.org/content/4/4/e353.full.pdf

**Comment by klemay** [comment] 2018-02-28 18:49
I noticed the HTML version of this article is loaded via AJAX - potentially related to this: https://github.com/hypothesis/product-backlog/issues/493

**Comment by judell** [comment] 2018-03-01 04:49
Duplicate of https://github.com/hypothesis/client/issues/671, should be closed in favor of that.

&lt;meta name="DC.Identifier" content="10.1212/NXI.0000000000000353">

**Comment by lyzadanger** [comment] 2020-10-09 15:16
Closing as duplicate of #671 as per @judell's suggestion.

**Closed by lyzadanger** 2020-10-09 15:16 UTC
