### ISSUE TITLE
inconsistent anchoring 

### ISSUE THREAD

**Issue by judell** [hypothesis/client#117] opened 2016-09-16 17:58 UTC
I've closed https://github.com/hypothesis/h/issues/3836 in favor of this issue.

The doc in question is a copyrighted PDF with this fingerprint: 4451dd7e09400643ada9a3b5edfe832a. (We have several copies internally.)

Here are two screencasts that illustrate the inconsistent behavior.

http://jonudell.net/h/bethesda-with-orphans-tab.mp4

In this example the orphans tab is enabled. I select "Bethesda, Maryland" once and create a normal annotation. I delete it, reselect "Bethesda, Maryland", and now create an orphan.

http://jonudell.net/h/bethesda-without-orphans-tab.mp4

Same example with the orphans tab off (as it is for all except a few H staffers). Similar behavior except the errant annotation is neither an orphan (in that it displays as an annotation card) nor an annotation (in that it does not behave like an anchored annotation).

The second example also illustrates another pathology I see intermittently on this doc: the adder sometimes fails to open the editor.

**Comment by robertknight** [comment] 2016-09-25 15:20
> The second example also illustrates another pathology I see intermittently on this doc:
> the adder sometimes fails to open the editor.

https://github.com/hypothesis/client/issues/122 describes a specific set of steps to reproduce a problem with the same symptoms in Chrome only.

**Comment by sean-roberts** [comment] 2016-10-19 22:12
Issue number two definitely shows the same visual result that #122 has. This is a result of an error being thrown between clicking and gathering the info about the selection. Without knowing if a JavaScript error I can't say 100% that it is the same error, but I have tracked down some information that helps us figure out #122. I will add my notes on that ticket. @judell if you can repro this and find that there is a JavaScript error that is not classList related, let me know.

**Comment by sean-roberts** [comment] 2016-10-19 22:58
I can only reproduce the adder doing the bouncing and not actually creating an annotation. I confirmed that the error I was seeing was the same JS error in #122 and it seemed to be working fine with my local branch that fixes #122 

I am still working to repro the orphan problem...

**Comment by robertknight** [comment] 2016-10-24 17:18
> I delete it, reselect "Bethesda, Maryland", and now create an orphan.

This is very likely a duplicate of #109 which I can now reproduce - new annotations getting created without a quote . As #122 is now fixed, I'm considering this a duplicate of #109 and closing it.

**Closed by robertknight** 2016-10-24 17:18 UTC
