### ISSUE TITLE
Adder squeezed on our own blog

### ISSUE THREAD

**Issue by dwhly** [hypothesis/client#416] opened 2017-06-05 13:52 UTC
### Steps to reproduce
1. Go here: https://web.hypothes.is/blog/fuzzy-anchoring/
2. Select text

### Expected behaviour
Normal adder should appear

### Actual behaviour
Adder is squeezed to half width

Not a good endorsement when we can't get the CSS right on our own pages.  cc @xolotl You should be aware of this.  Perhaps there's something we can do on our end quicker to fix?

### Browser/system information
Chrome

### Additional details

![screen shot 2017-06-05 at 6 50 30 am](https://cloud.githubusercontent.com/assets/1413074/26786392/4fb66100-49bb-11e7-852a-a007d8ee8971.png)

**Comment by xolotl** [comment] 2017-06-05 17:28
Looks like an issue with a style rule `word-break: break-word;` on web.hypothes.is designed to help deal with very long text lines, like the line `<link rel="canonical" href="http://www.theatlantic.com/magazine/archive/1945/07/as-we-may-think/303881/" />` on this blog post: https://web.hypothes.is/blog/cross-format-annotation/

This intervention was based on an approach here: https://css-tricks.com/snippets/css/prevent-long-urls-from-breaking-out-of-container/

I seems like  `word-break: break-word;` may not be a necessary ingredient in breaking long lines, so I'll remove it from the web.hypothes.is styles, however the Hypothesis client may encounter it elsewhere and so might want to handle those cases.

**Comment by xolotl** [comment] 2017-06-05 18:38
resolved on web.hypothes.is via https://github.com/hypothesis/webhypothesis/commit/e84fe9157bd6eaf4c7fd0ee67de9fd3f87ed0676

**Comment by robertknight** [comment] 2017-06-05 20:53
@xolotl - The issue is fixed in the next client release which protects the "adder" from inheriting style values from the page.

**Comment by robertknight** [comment] 2017-06-07 09:08
The issue in the client was fixed in v1.20.

**Closed by robertknight** 2017-06-07 09:08 UTC
