### ISSUE TITLE
Refactor API surface and organization of bucket-calculation utils

### ISSUE THREAD

**Issue by lyzadanger** [hypothesis/client#2618] opened 2020-10-07 12:41 UTC
Recent coffeescript -> JS migration of `plugin/bucket-bar` involved extracting the calculation of buckets and their positions into `util/buckets`. The API for these functions was left intact from legacy code, and involves some somewhat convoluted data structures and organization.

Refactor these such that their API and types are more intuitive.

This will reduce the likelihood of bugs (e.g. currently buckets and their positions are maintained in two separate Arrays that could get out of sync) and make it easier to extend and change this code in the future.

**Comment by robertknight** [comment] 2020-10-07 13:28
Related Slack discussion: https://hypothes-is.slack.com/archives/C1M8NH76X/p1602074427209000

From looking over the code this morning, the main potential improvements that jumped out at me were:

- Avoiding potential errors caused by mismatches in parallel arrays (pairs of arrays that contain different parts of the data for the same entity)
- Simplifying the reduction of anchors into buckets by resolving each anchor to a single point (the Y coordinate where the annotation's content starts) rather than dealing with ranges
- Fixing the cause of empty buckets being created, which is confusing when looking at the DOM

I'm sure Lyza has other things to add here.

**Closed** 2020-10-21 12:54 UTC
Labels: client tech debt
