### ISSUE TITLE
Rename highlights class name issue

### ISSUE THREAD

**Issue by discodavey** [hypothesis/client#1853] opened 2020-02-28 11:07 UTC
### Steps to reproduce
1. We are aware this is a hack but on changing the highlights class https://github.com/hypothesis/client/pull/1775 caused the colours on our site to change to the defaults that Hypothesis provide.
2. This is reference to: https://github.com/elifesciences/pattern-library/pull/968

### Expected behaviour
We have CSS that overrides the default highlight colours to fit in more with our brand.

### Actual behaviour
The default colours were showing due to the css class name change

### Browser/system information
All browsers

### Additional details
This is not a bug as such from Hypothesis but caused and issue from our side. 

May we suggest an idea of making the highlights class configurable so colours can be changed to fit in with the brand of the relevant site?

**Comment by robertknight** [comment] 2020-02-28 13:35
> May we suggest an idea of making the highlights class configurable so colours can be changed to fit in with the brand of the relevant site?

How much flexibility do you need? Allowing the site to make arbitrary style changes could handicap us in future. However I could imagine that we could provide a way for the site to supply a base color for highlights.

Also, can you tell us about your constraints in terms of browser support? One way that customization _might_ work is to make use of CSS variables. That would not be available in IE however (though we could provide some fallback to a default in that case).

**Comment by robertknight** [comment] 2021-03-18 11:42
I'm closing this issue because there hasn't been a response to my previous query. I'm happy to re-open if the issue is still applicable.

**Closed by robertknight** 2021-03-18 11:42 UTC
