### ISSUE TITLE
Share annotations copy button is not working in Safari

### ISSUE THREAD

**Issue by robertknight** [hypothesis/client#5196] opened 2023-01-25 13:36 UTC
The copy button in the "Share annotation" dialog does not work in Safari 16. It does work in Chrome and Firefox.

<img width="409" alt="Share link copy button" src="https://user-images.githubusercontent.com/2458/214577577-1fcd1119-8efe-498d-8bdc-646839807bac.png">

**Steps to reproduce:**

1. Click the "Share annotation" toolbar button on an annotation
2. Click the "Copy" button

**Expected result:** - Link should be copied and a toast message should be shown in the sidebar
**Actual result (in Safari):** - The share popup disappears, but nothing is copied to the clipboard and no toast message is displayed

**Comment by lyzadanger** [comment] 2023-01-26 13:48
I’ve got a cause! It took me a little while to nail it down as there is a fair amount of event complexity in the UI context involved. This sent me down several red-herring ratholes before I was able to isolate the culprit.

This panel should close when mousedown/clicks or focus events occur in elements _outside_ of it. This allows users to click or set focus on elements elsewhere in the UI and dismiss the panel.

However, when the copy button in the panel is clicked in Safari, the panel closes before the button handler is triggered, meaning that the URL does not get successfully copied.

**Cause**

* Safari differs from other browsers in that it does not set `focus` on the copy button when it is clicked in the panel. Safari’s behavior in this regard is [certified crazypants and has been a bone of contention for years](https://bugs.webkit.org/show_bug.cgi?id=22261).

**Additional relevant behavior (a plane crash never has a single cause, right?):**

* Clicking on a non-focusable element within the panel will cause it to close in any browser. This behavior is incorrect (the panel should only close if there are clicks or focus _outside_ of it) and contributes toward the buggy Safari behavior.
* The copy-to-clipboard code, triggered by button clicks in non-Safari browsers, steals focus. It sets focus on a temporary `textarea` element and does not restore it. This also causes the panel to close (as it causes a focus event outside of the panel).
* The share-annotation panel itself routes focus to an input element when it’s opened. This is mostly a red herring, but adds to the noise of focus thrash.

**Explanation of behavior:**

Clicking on any non-focusable area in the panel in non-Safari browsers causes the panel to close because it results in a `focus` event being triggered outside of the panel. Why, you may ask?

Share-annotation panels are children of the annotation card (`ThreadCard`) to which they correspond, DOM-wise. `ThreadCard`s (their outer container `div`) are focusable. There are two odd things about this. 

One, `div`s are not focusable elements normally. However, we’ve added a non-null `tabindex` to `ThreadCard` divs, as well as click handlers. This is to allow the whole annotation card to be clicked, and that click to cause the guest frame to scroll to the associated annotation highlight.

Two, we end up with a situation of nested focusable elements. Any click within an annotation card — this includes the annotation panel and its contents — is going to focus something: either the element clicked (if it’s focusable) or the entire annotation card (if what was clicked doesn’t trigger focus on itself).

In normal non-stupid browsers, clicking on the copy button sets focus on the button, because buttons are focusable. Thus there are both click and focus events within the panel, which does not close the panel. The panel does close, but this is caused by the copy-to-clipboard code stealing focus (see above). 

In Safari, clicking on the copy button does not set focus on it. Instead the focus “falls out” to the annotation card as the nearest containing focusable element. Similar to clicking on a non-focusable element described above, this causes the panel to close. And it closes (unmounts, goes away, poof) before the button handler is executed.

**Problems to solve:**

* Clicks anywhere within the share-annotation panel should not focus the annotation card in any circumstance. There are a few ways I can think of doing this.
* Copy-to-clipboard should restore focus. 
* The panel should be explicitly closed by its component at the conclusion of its button handler (i.e. it should still close after the URL is copied, but that won’t happen automatically anymore once the above items are addressed).

I might not address all of these in one swoop; first stop is to get the feature to work at all in Safari.

**Comment by robertknight** [comment] 2023-01-26 13:56
> Copy-to-clipboard should restore focus.

Since that code was written, a [browser API](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API) for interacting with the clipboard was added, which is now supported by essentially all of the browsers we support. That would avoid the textarea entirely. I think we looked at this in the past and decided not to use the new API for some reason, might be worth revisiting that.

**Closed** 2023-01-26 15:15 UTC
