### ISSUE TITLE
Client doesn't open on LinkedIn Pulse pages

### ISSUE THREAD

**Issue by seanh** [hypothesis/client#479] opened 2017-06-30 14:41 UTC
For example go to this page: <https://www.linkedin.com/pulse/feed/channel/227?trk=pulse-cat-rec-chn_card-img-5> or any of these <https://www.linkedin.com/pulse/discover>. When you click the Chrome extension button to open the client, nothing happens (no sidebar). I didn't see any failed network requests or any errors in the console (either host page or extension's background page).

**Comment by dwhly** [comment] 2017-07-03 20:51
I'll just give this a bump.  Definitely an important one to fix.

**Comment by robertknight** [comment] 2017-07-15 22:10
The problem is a JS conflict with the environment. The page declares a function called `define` which is part of an AMD-style module system. One of the JS modules ([dom-anchor-fragment](https://github.com/tilgovi/dom-anchor-fragment)) used by `src/annotator` is a [UMD module](https://github.com/umdjs/umd) which tests for the existence of `define` and if found, assumes that it is in an AMD environment and attempts to call it instead of assigning to `module.exports`. The call is incompatible and triggers an error.

**Comment by judell** [comment] 2019-04-16 19:20
Seemingly related: at https://www.fulcrum.org/epubs/w0892c07h?locale=en#/6/6[Brennan-0003]!/4/2/4[pii]/1:0, this happens:

```
Uncaught Error: See almond README: incorrect module build, no module name
    at define (application-9b73cd6bad93030936f2da2f4cafbea5313b43617cadd339be1295ac72cba7b6.js:524)
    at annotator.bundle.js?f48ba3:20
    at Object.6 (annotator.bundle.js?f48ba3:20)
    at o (annotator.bundle.js?f48ba3:1)
    at annotator.bundle.js?f48ba3:1
    at Object.39../range (annotator.bundle.js?f48ba3:131)
    at o (annotator.bundle.js?f48ba3:1)
    at annotator.bundle.js?f48ba3:1
    at Object.36../types (annotator.bundle.js?f48ba3:122)
    at o (annotator.bundle.js?f48ba3:1)
```

Reported by Jon McGlone at Michigan Publishing. His message:

> We believe the error is happening because of the way hypothesis distribution is built conflicting with our application. Our application uses a define function that in newer Almond (which the Rails pipeline uses) requires a first parameter that is the module name.

**Comment by robertknight** [comment] 2019-04-18 17:55
The LinkedIn URLs appear to be broken, nevertheless this issue has been affecting some other sites and publishers wishing to use Hypothesis. The problematic code in the client serves little value (IMO) so I posted a PR to just remove it.

**Closed** 2019-04-23 05:13 UTC
Labels: P4: Three months, Project: Bug fixes, Website Environment Conflict
