### ISSUE TITLE
the dc:title of metadata is empty but not treated as Untitled

### ISSUE THREAD

**Issue by gylns** [hypothesis/client#683] opened 2018-03-03 14:42 UTC
I noticed that when annotating a PDF file, the title is display as "Untitled document", I checked the code of the server, and found that it is because of the title of the metadata sent by the client is empty.
Here is the code of the client get the title of metadata:
`if (app.metadata && app.metadata.has('dc:title') && app.metadata.get('dc:title') !== 'Untitled') {
      title = app.metadata.get('dc:title');
    }` 
It only checked the case that the title is not 'Untitled' and forgot the empty case.

Moreover, can I edit the title and url fields of an annotation?

**Comment by robertknight** [comment] 2021-08-23 17:44
Duplicate of https://github.com/hypothesis/client/issues/763.

**Closed by robertknight** 2021-08-23 17:44 UTC
Labels: PDF
