### ISSUE TITLE
annotation fails at http://www.matthewcornell.org/blog/2015/8/31/a-simple-fabricjs-based-web-app-for-annotating-svg-files.html 

### ISSUE THREAD

**Issue by judell** [hypothesis/client#288] opened 2017-03-15 03:05 UTC
### Steps to reproduce
1. http://www.matthewcornell.org/blog/2015/8/31/a-simple-fabricjs-based-web-app-for-annotating-svg-files.html
2. Try to annotate

### Expected behaviour
It works.

### Actual behaviour
Uncaught (in promise) TypeError: Cannot read property '$tag' of undefined
    at t.beforeAnnotationCreated (annotation-sync.coffee:55)
    at HTMLBodyElement.<anonymous> (global.js?CE=75:1)
    at HTMLBodyElement.o (annotator.js:446)
    at HTMLBodyElement.dispatch (jquery.js:4641)
    at HTMLBodyElement.g.handle (jquery.js:4309)
    at Object.trigger (jquery.js:4550)
    at ie.fn.init.triggerHandler (jquery.js:5266)
    at e.publish (annotator.js:439)
    at guest.coffee:327

**Comment by seanh** [comment] 2017-03-20 13:14
Confirmed, I can reproduce this in production

**Comment by seanh** [comment] 2017-03-20 14:29
After some investigation, `http://www.matthewcornell.org/blog/2015/8/31/a-simple-fabricjs-based-web-app-for-annotating-svg-files.html` [contains this JavaScript code](http://www.matthewcornell.org/universal/scripts/global.js):

```javascript
Function.prototype.bind = function(I, N, M, L, J, H, G, F, C, B, A) {
    var K = this;
    return function() {
        K.apply(I, [N, M, L, J, H, G, F, C, B, A]);
    }
    ;
}
;
```

Which is redefining a fundamental part of the programming language environment in a way that breaks our code. Exactly what happens I don't know, but an `annotation` argument that's being passed down the call stack in our code is at some point (when it passes through the bind function above) being turned from an object into `undefined`, which our `annotation-sync.coffee` code doesn't expect.

@robertknight This sounds like another case where we need to protect our `src/annotator/` from other JavaScript running in the document. Anything we can do here in the short term?

**Comment by seanh** [comment] 2017-03-20 15:28
Related: https://github.com/hypothesis/product-backlog/issues/148

**Comment by seanh** [comment] 2017-03-20 15:30
Closing this as a duplicate of https://github.com/hypothesis/client/issues/245

**Closed by seanh** 2017-03-20 15:30 UTC
Labels: Website Environment Conflict
